# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 650)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(310, 513, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.msgTextBrowser = QtWidgets.QTextBrowser(Form)
        self.msgTextBrowser.setGeometry(QtCore.QRect(20, 43, 391, 451))
        self.msgTextBrowser.setObjectName("msgTextBrowser")
        self.msgLineEdit = QtWidgets.QLineEdit(Form)
        self.msgLineEdit.setGeometry(QtCore.QRect(21, 514, 271, 71))
        self.msgLineEdit.setObjectName("msgLineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "전송"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
