# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 650)
        self.nicknameLabel = QtWidgets.QLabel(Dialog)
        self.nicknameLabel.setGeometry(QtCore.QRect(40, 288, 151, 31))
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.nicknameTextEdit = QtWidgets.QTextEdit(Dialog)
        self.nicknameTextEdit.setGeometry(QtCore.QRect(40, 318, 241, 31))
        self.nicknameTextEdit.setObjectName("nicknameTextEdit")
        self.connectButton = QtWidgets.QPushButton(Dialog)
        self.connectButton.setGeometry(QtCore.QRect(300, 318, 121, 31))
        self.connectButton.setObjectName("connectButton")
        self.portLabel = QtWidgets.QLabel(Dialog)
        self.portLabel.setGeometry(QtCore.QRect(40, 213, 151, 31))
        self.portLabel.setObjectName("portLabel")
        self.portTextEdit = QtWidgets.QTextEdit(Dialog)
        self.portTextEdit.setGeometry(QtCore.QRect(40, 243, 241, 31))
        self.portTextEdit.setObjectName("portTextEdit")
        self.ipLabel = QtWidgets.QLabel(Dialog)
        self.ipLabel.setGeometry(QtCore.QRect(40, 144, 151, 31))
        self.ipLabel.setObjectName("ipLabel")
        self.ipTextEdit = QtWidgets.QTextEdit(Dialog)
        self.ipTextEdit.setGeometry(QtCore.QRect(40, 174, 241, 31))
        self.ipTextEdit.setObjectName("ipTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nicknameLabel.setText(_translate("Dialog", "닉네임을 정해주세요"))
        self.connectButton.setText(_translate("Dialog", "채팅방 입장"))
        self.portLabel.setText(_translate("Dialog", "PORT"))
        self.ipLabel.setText(_translate("Dialog", "IP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
